kind: pipeline
type: kubernetes
name: default

steps:
- name: kaniko
  image: plugins/docker
  settings:
    username: zhala
    password: 
      from_secret: docker-password
    repo: zhala/utils-image
    tags: latest