kind: pipeline
type: kubernetes
name: default

steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    registry: hub.docker.com
    username: zhala
    password: 
      from_secret: docker-password
    repo: zhala/utils-image
    tags: latest