kind: pipeline
type: kubernetes
name: default

# services:
#   - name: docker
#     image: docker:dind
#     privileged: true

steps:
- name: build-image
  image: plugins/docker
  settings:
    username: zhala
    password: 
      from_secret: docker-password
    repo: zhala/utils-image
    tags: latest

# - name: Anchore Grype
#   commands:
#     - /usr/local/bin/docker-grype-cmd.sh
#   environment:
#     DOCKER_HOST: tcp://docker:2375
#     IMAGE_NAME: zhala/utils-image:latest
#   image: cbdq/docker-grype:latest
#   pull: if-not-exists
