kind: pipeline
type: kubernetes
name: default

steps:
- name: build-image
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    username: zhala
    password: 
      from_secret: docker-password
    repo: zhala/utils-image
    tags: latest
    platforms: amd64, arm64