kind: pipeline
type: kubernetes
name: default

# services:
#   - name: docker
#     image: docker:dind
#     privileged: true

steps:
- name: build-image
  image: plugins/docker
  settings:
    username: zhala
    password: 
      from_secret: docker-password
    repo: zhala/utils-image
    tags: latest
    mtu: 1440

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack-build-webhook
    template: |
      {{#success build.status}} :white_check_mark: {{ else }} :x: {{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }} * (type: `{{ build.event }}`)
      Commit: <{{ build.source_repo }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
      Build: <{{ build.link }}| Drone Build {{ build.number }}>
  when:
    status:
    - success
    - failure

# - name: Anchore Grype
#   commands:
#     - /usr/local/bin/docker-grype-cmd.sh
#   environment:
#     DOCKER_HOST: tcp://docker:2375
#     IMAGE_NAME: zhala/utils-image:latest
#   image: cbdq/docker-grype:latest
#   pull: if-not-exists
