kind: pipeline
type: kubernetes
name: default

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

steps:
- name: build-image-internal
  image: plugins/docker
  settings:
    registry: registry.zanelab.com
    repo: registry.zanelab.com/zhala/utils-image
    tags: 
      - ${DRONE_BUILD_NUMBER}
      - latest
  # Only run this step when a PR is opened or a commit is pushed
  # on a non master branch
  when:
    branch:
      exclude:
      - master
    event: 
    - push
    - pull_request

- name: build-image-public
  image: plugins/docker
  settings:
    username: zhala
    password: 
      from_secret: docker-password
    repo: zhala/utils-image
    tags: latest
    mtu: 1440
  # Only run this step when a PR is merged into master
  when:
    branch: master
    event: 
    - push

- name: Generate SBOM and Vulns
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker run anchore/grype zhala/utils-image:latest

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack-build-webhook
    template: |
      {{#success build.status}} :white_check_mark: {{ else }} :x: {{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }} * (type: `{{ build.event }}`)
      Commit: <${DRONE_COMMIT_LINK}|{{ truncate build.commit 8 }}>
      Build: <{{ build.link }}| Drone Build {{ build.number }}>
      Branch: ${DRONE_BRANCH}
  when:
    status:
    - success
    - failure
